const FILE_NAME = "test.txt";
const DATE_FORMAT_HEADER = "YYMMDD";
const DATE_FORMAT_DATA = "YYYYMMDD";
const INDEX_NUMBER_HEADER_ALL = "All Indices";
const INDEX_NUMBER_HEADER_OTHERS = "the noted index only";

const RECORD_TYPE = {
  HEADER: "01",
  DATA: "02",
  FREE_FLOAT_DATA: "03",
  TRAILER: "99"
};

const INDEX_TYPE_HEADER = {
  ALL_INDICES: "0",
  SECURITY_INDICES: "1",
  BOND_INDICES: "2"
};

const TASE_FILE_ID_CHRS_HEADER = {
  WEIGHT_OF_SECURITIES_IN_INDICES: "0161",
  WEIGHT_OF_SECURITIES_IN_REZEF_INDICES: "0162"
};

const INDEX_TYPE_DATA = {
  SHARES: "00",
  GOVERNMENT_BONDS: "01",
  CORPORATE_BONDS: "10",
  GOVERNMENT_AND_CORPORATE_BONDS: "11"
};

module.exports = {
  FILE_NAME,
  DATE_FORMAT_HEADER,
  DATE_FORMAT_DATA,
  INDEX_NUMBER_HEADER_ALL,
  INDEX_NUMBER_HEADER_OTHERS,
  RECORD_TYPE,
  INDEX_TYPE_HEADER,
  TASE_FILE_ID_CHRS_HEADER,
  INDEX_TYPE_DATA
};
